import { useState, useRef } from "react"
import { toPng } from "html-to-image"
import confetti from "canvas-confetti"
import {
  X,
  Download,
  Share2,
  Copy,
  Check,
  Sparkles,
  Palette,
  Eye,
  Smartphone,
  Maximize2,
  MessageCircle,
  RefreshCw
} from "lucide-react"
import { TwitterIcon, LinkedinIcon } from "../ui/Icons"
import ShareCard, { defaultCustomization } from "./ShareCard"
import type { CardCustomization } from "./ShareCard"
import type { Developer } from "../../data/mockData"

interface ShareCardModalProps {
  developer: Developer | null
  isOpen: boolean
  onClose: () => void
}

export default function ShareCardModal({ developer, isOpen, onClose }: ShareCardModalProps) {
  if (!isOpen || !developer) return null

  const cardContainerRef = useRef<HTMLDivElement>(null)
  const [config, setConfig] = useState<CardCustomization>({
    ...defaultCustomization,
    style: developer.rank === 1 ? "gold" : developer.rank <= 3 ? "cosmic" : developer.rank <= 10 ? "cyber" : "neon"
  })
  const [isExporting, setIsExporting] = useState(false)
  const [copiedLink, setCopiedLink] = useState(false)
  const [activeTab, setActiveTab] = useState<"style" | "layout" | "share">("style")

  const triggerConfetti = () => {
    confetti({
      particleCount: 75,
      spread: 60,
      origin: { y: 0.7 },
      colors: ["#6366f1", "#38bdf8", "#ec4899", "#f59e0b"]
    })
  }

  const handleDownload = async () => {
    if (!cardContainerRef.current) return
    try {
      setIsExporting(true)
      const dataUrl = await toPng(cardContainerRef.current, {
        cacheBust: true,
        pixelRatio: 2.5,
        backgroundColor: "#030712",
      })

      const link = document.createElement("a")
      link.download = `gitrank-${developer.username}-card.png`
      link.href = dataUrl
      link.click()

      triggerConfetti()
    } catch (err) {
      console.error("Failed to generate card image:", err)
    } finally {
      setIsExporting(false)
    }
  }

  const handleCopyLink = async () => {
    const url = `${window.location.origin}/card/${developer.username}`
    await navigator.clipboard.writeText(url)
    setCopiedLink(true)
    triggerConfetti()
    setTimeout(() => setCopiedLink(false), 2500)
  }

  const handleNativeShare = async () => {
    const url = `${window.location.origin}/card/${developer.username}`
    if (navigator.share) {
      try {
        await navigator.share({
          title: `${developer.name}'s GitRank Card`,
          text: `Check out ${developer.name} ranked #${developer.rank} on GitRank!`,
          url,
        })
      } catch {
        // Fallback copy if cancelled or rejected
      }
    } else {
      handleCopyLink()
    }
  }

  const shareText = encodeURIComponent(`I just checked out ${developer.name} ranked #${developer.rank} on GitRank! 🚀 Check out their developer card:`)
  const cardUrl = encodeURIComponent(`${window.location.origin}/card/${developer.username}`)

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-6 bg-black/80 backdrop-blur-md animate-in fade-in duration-200">
      <div className="relative w-full max-w-5xl max-h-[92vh] overflow-hidden rounded-2xl bg-slate-900 border border-slate-800 shadow-2xl flex flex-col md:flex-row text-slate-100">
        
        {/* Close button */}
        <button
          onClick={onClose}
          className="absolute top-4 right-4 z-20 p-2 rounded-full bg-slate-800/80 hover:bg-slate-700 text-slate-400 hover:text-white border border-slate-700 transition"
        >
          <X className="w-5 h-5" />
        </button>

        {/* LEFT COLUMN: LIVE CARD PREVIEW */}
        <div className="flex-1 bg-gradient-to-b from-slate-950 via-[#060813] to-slate-950 p-6 flex flex-col items-center justify-center border-b md:border-b-0 md:border-r border-slate-800/80 overflow-y-auto min-h-[380px]">
          <div className="text-center mb-4">
            <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-semibold bg-indigo-500/10 text-indigo-300 border border-indigo-500/20">
              <Sparkles className="w-3.5 h-3.5 text-indigo-400" /> Interactive 3D Preview (Hover & Tilt)
            </span>
          </div>

          <div className="transform scale-90 sm:scale-100 transition-all origin-center">
            <ShareCard
              developer={developer}
              customization={config}
              isInteractive={true}
              cardRef={cardContainerRef}
            />
          </div>

          <p className="text-[11px] text-slate-500 mt-4 text-center">
            High-res export (1080×1350 HD PNG) • Generated by GitRank Analytics
          </p>
        </div>

        {/* RIGHT COLUMN: CONTROLS & ACTIONS */}
        <div className="w-full md:w-[420px] bg-slate-900 p-6 flex flex-col justify-between overflow-y-auto">
          <div>
            {/* Header */}
            <div className="mb-5">
              <h2 className="text-xl font-bold text-white flex items-center gap-2">
                <Sparkles className="w-5 h-5 text-indigo-400" /> Card Studio
              </h2>
              <p className="text-xs text-slate-400 mt-0.5">
                Customize your collectible ranking card for social media.
              </p>
            </div>

            {/* Navigation Tabs */}
            <div className="flex border-b border-slate-800 mb-5 text-xs font-semibold">
              <button
                onClick={() => setActiveTab("style")}
                className={`flex items-center gap-1.5 pb-2.5 px-3 border-b-2 transition ${
                  activeTab === "style"
                    ? "border-indigo-500 text-indigo-400"
                    : "border-transparent text-slate-400 hover:text-slate-200"
                }`}
              >
                <Palette className="w-3.5 h-3.5" /> Style & Theme
              </button>
              <button
                onClick={() => setActiveTab("layout")}
                className={`flex items-center gap-1.5 pb-2.5 px-3 border-b-2 transition ${
                  activeTab === "layout"
                    ? "border-indigo-500 text-indigo-400"
                    : "border-transparent text-slate-400 hover:text-slate-200"
                }`}
              >
                <Eye className="w-3.5 h-3.5" /> Data Badges
              </button>
              <button
                onClick={() => setActiveTab("share")}
                className={`flex items-center gap-1.5 pb-2.5 px-3 border-b-2 transition ${
                  activeTab === "share"
                    ? "border-indigo-500 text-indigo-400"
                    : "border-transparent text-slate-400 hover:text-slate-200"
                }`}
              >
                <Share2 className="w-3.5 h-3.5" /> Share & Export
              </button>
            </div>

            {/* TAB 1: STYLE CONTROLS */}
            {activeTab === "style" && (
              <div className="space-y-4">
                {/* Rarity & Theme Preset */}
                <div>
                  <label className="text-xs font-medium text-slate-300 block mb-1.5 flex items-center justify-between">
                    <span>Card Aesthetic Preset</span>
                    <span className="text-[10px] text-indigo-400 capitalize">{config.style} Theme</span>
                  </label>
                  <div className="grid grid-cols-3 gap-2">
                    {[
                      { id: "neon", label: "Neon", border: "border-indigo-500" },
                      { id: "cyber", label: "Cyber", border: "border-cyan-500" },
                      { id: "gold", label: "Gold", border: "border-amber-500" },
                      { id: "cosmic", label: "Cosmic", border: "border-fuchsia-500" },
                      { id: "minimal", label: "Minimal", border: "border-slate-500" },
                    ].map((st) => (
                      <button
                        key={st.id}
                        onClick={() => setConfig({ ...config, style: st.id as any })}
                        className={`p-2 rounded-lg text-xs font-medium border text-center transition ${
                          config.style === st.id
                            ? `${st.border} bg-indigo-500/10 text-white font-bold`
                            : "border-slate-800 bg-slate-950/60 text-slate-400 hover:border-slate-700"
                        }`}
                      >
                        {st.label}
                      </button>
                    ))}
                  </div>
                </div>

                {/* Background Texture */}
                <div>
                  <label className="text-xs font-medium text-slate-300 block mb-1.5">
                    Background Pattern
                  </label>
                  <div className="grid grid-cols-3 gap-2">
                    {[
                      { id: "tech", label: "Developer Tech" },
                      { id: "grid", label: "Matrix Grid" },
                      { id: "abstract", label: "Deep Space" },
                      { id: "gradient", label: "Gradient" },
                      { id: "dark", label: "Onyx Dark" },
                    ].map((bg) => (
                      <button
                        key={bg.id}
                        onClick={() => setConfig({ ...config, background: bg.id as any })}
                        className={`p-2 rounded-lg text-xs font-medium border text-center transition ${
                          config.background === bg.id
                            ? "border-indigo-500 bg-indigo-500/10 text-white font-bold"
                            : "border-slate-800 bg-slate-950/60 text-slate-400 hover:border-slate-700"
                        }`}
                      >
                        {bg.label}
                      </button>
                    ))}
                  </div>
                </div>

                {/* Aspect Ratio Presets */}
                <div>
                  <label className="text-xs font-medium text-slate-300 block mb-1.5">
                    Dimensions / Social Format
                  </label>
                  <div className="grid grid-cols-2 gap-2">
                    <button
                      onClick={() => setConfig({ ...config, aspectRatio: "portrait" })}
                      className={`p-2 rounded-lg text-xs font-medium border flex items-center justify-center gap-1.5 transition ${
                        config.aspectRatio === "portrait"
                          ? "border-indigo-500 bg-indigo-500/10 text-white font-bold"
                          : "border-slate-800 bg-slate-950/60 text-slate-400 hover:border-slate-700"
                      }`}
                    >
                      <Smartphone className="w-3.5 h-3.5" /> 4:5 Instagram Post
                    </button>
                    <button
                      onClick={() => setConfig({ ...config, aspectRatio: "story" })}
                      className={`p-2 rounded-lg text-xs font-medium border flex items-center justify-center gap-1.5 transition ${
                        config.aspectRatio === "story"
                          ? "border-indigo-500 bg-indigo-500/10 text-white font-bold"
                          : "border-slate-800 bg-slate-950/60 text-slate-400 hover:border-slate-700"
                      }`}
                    >
                      <Maximize2 className="w-3.5 h-3.5" /> 9:16 Story / Reels
                    </button>
                  </div>
                </div>
              </div>
            )}

            {/* TAB 2: DATA BADGES TOGGLES */}
            {activeTab === "layout" && (
              <div className="space-y-2.5">
                <p className="text-xs text-slate-400 mb-2">
                  Toggle which elements to display on your collectible card:
                </p>
                {[
                  { key: "showRank", label: "Global Rank Badge" },
                  { key: "showScore", label: "GitRank Score & Ring" },
                  { key: "showArchetype", label: "Developer Archetype Banner" },
                  { key: "showStars", label: "GitHub Stars" },
                  { key: "showFollowers", label: "Followers Count" },
                  { key: "showContributions", label: "Annual Contributions" },
                  { key: "showLanguages", label: "Primary Programming Language" },
                  { key: "showQrCode", label: "Verification QR Code" },
                  { key: "showUsername", label: "GitHub @Username" },
                ].map((item) => (
                  <label
                    key={item.key}
                    className="flex items-center justify-between p-2 rounded-lg bg-slate-950/50 border border-slate-800/80 cursor-pointer hover:border-slate-700 text-xs"
                  >
                    <span className="text-slate-300 font-medium">{item.label}</span>
                    <input
                      type="checkbox"
                      checked={(config as any)[item.key]}
                      onChange={(e) =>
                        setConfig({ ...config, [item.key]: e.target.checked })
                      }
                      className="w-4 h-4 rounded text-indigo-600 bg-slate-900 border-slate-700 focus:ring-indigo-500"
                    />
                  </label>
                ))}
              </div>
            )}

            {/* TAB 3: SHARE CHANNELS */}
            {activeTab === "share" && (
              <div className="space-y-4">
                <div className="p-3 rounded-xl bg-indigo-950/40 border border-indigo-500/20 text-xs text-indigo-200">
                  ⚡ Your card has a dedicated public URL anyone can visit directly at <code className="font-mono text-indigo-300">/card/{developer.username}</code>
                </div>

                <div className="space-y-2">
                  <a
                    href={`https://twitter.com/intent/tweet?text=${shareText}&url=${cardUrl}`}
                    target="_blank"
                    rel="noreferrer"
                    className="w-full flex items-center justify-center gap-2 py-2.5 px-4 rounded-xl bg-[#1d9bf0]/10 hover:bg-[#1d9bf0]/20 text-[#1d9bf0] border border-[#1d9bf0]/30 font-semibold text-xs transition"
                  >
                    <TwitterIcon className="w-4 h-4" /> Share on X / Twitter
                  </a>
                  <a
                    href={`https://www.linkedin.com/sharing/share-offsite/?url=${cardUrl}`}
                    target="_blank"
                    rel="noreferrer"
                    className="w-full flex items-center justify-center gap-2 py-2.5 px-4 rounded-xl bg-[#0a66c2]/10 hover:bg-[#0a66c2]/20 text-[#0a66c2] border border-[#0a66c2]/30 font-semibold text-xs transition"
                  >
                    <LinkedinIcon className="w-4 h-4" /> Share on LinkedIn
                  </a>
                  <a
                    href={`https://api.whatsapp.com/send?text=${shareText}%20${cardUrl}`}
                    target="_blank"
                    rel="noreferrer"
                    className="w-full flex items-center justify-center gap-2 py-2.5 px-4 rounded-xl bg-[#25d366]/10 hover:bg-[#25d366]/20 text-[#25d366] border border-[#25d366]/30 font-semibold text-xs transition"
                  >
                    <MessageCircle className="w-4 h-4" /> Share to WhatsApp
                  </a>
                </div>
              </div>
            )}
          </div>

          {/* BOTTOM ACTION BUTTONS */}
          <div className="pt-5 border-t border-slate-800 space-y-2.5">
            <button
              onClick={handleDownload}
              disabled={isExporting}
              className="w-full flex items-center justify-center gap-2 py-3 px-4 rounded-xl bg-gradient-to-r from-indigo-500 to-sky-500 hover:from-indigo-600 hover:to-sky-600 text-white font-bold text-sm shadow-lg shadow-indigo-500/25 transition disabled:opacity-50"
            >
              {isExporting ? (
                <>
                  <RefreshCw className="w-4 h-4 animate-spin" /> Generating High-Res PNG...
                </>
              ) : (
                <>
                  <Download className="w-4 h-4" /> Download PNG Card
                </>
              )}
            </button>

            <div className="grid grid-cols-2 gap-2">
              <button
                onClick={handleNativeShare}
                className="flex items-center justify-center gap-1.5 py-2.5 px-3 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-200 font-semibold text-xs border border-slate-700 transition"
              >
                <Share2 className="w-3.5 h-3.5 text-sky-400" /> Share Card
              </button>

              <button
                onClick={handleCopyLink}
                className="flex items-center justify-center gap-1.5 py-2.5 px-3 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-200 font-semibold text-xs border border-slate-700 transition"
              >
                {copiedLink ? (
                  <>
                    <Check className="w-3.5 h-3.5 text-emerald-400" /> Link Copied!
                  </>
                ) : (
                  <>
                    <Copy className="w-3.5 h-3.5 text-indigo-400" /> Copy Card Link
                  </>
                )}
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
